#ifndef TRUECRACKCPP_SRC_MAIN_CORE_CRYPTO_ENCRYPTION_MODE_ENCRYPTION_MODE_H_
#define TRUECRACKCPP_SRC_MAIN_CORE_CRYPTO_ENCRYPTION_MODE_ENCRYPTION_MODE_H_

namespace crypto {

class EncryptionMode {
 public:

};

} // crypto

#endif //TRUECRACKCPP_SRC_MAIN_CORE_CRYPTO_ENCRYPTION_MODE_ENCRYPTION_MODE_H_
